### PR TITLE
Added Visual Studio Code to pkg installer

### PR DESCRIPTION
**Pull request by Rafcin**
I added a Visual Studio Code to the pkg installer, its not clean but it should install it correctly on all the Jetson devices and its a much better editor than Gedit or other arm based editors.

### CODE REVIEW

**Comment by rbonghi** [comment]
Thank you @Rafcin I'm checking!

**Comment by Rafcin** [comment]
Awesome! The gist files if they correctly install will replace the ones in VS and compile with Electron, if they do then all is good 👍. Also VSCode hopefully will be useful to people because of it's customization features + workspace and git control.

**Comment by rbonghi** [comment]
I have only fixed the size of the window and add an extra comment on the patch menu about the wifi fix.

**Comment by Rafcin** [comment]
Awesome!

**Comment by Rafcin** [comment]
I'm going to add some more stuff over the weekend regarding ROS Melodic, there's a lot of bugs I've found over time that probably should be looked at. Also have you considered switching the catkin_make to Catkin build?

**Comment by Rafcin** [comment]
Also one thing that I think will be useful is adding RTABMAP and having it compile from scratch becuase it allows you to also use the Zed SDK vs when you install it through apt it doesn't have that enabled/pathway set.

**Pull request merged**
